import 'package:cloud_firestore/cloud_firestore.dart';

class Annonce {
  String? id,
      ville,
      cite,
      categorie,
      title,
      aroundCityDistance,
      aroundAirportDistance,
      aroundTrainDistance,
      aroundMetroDistance,
      aroundBusDistance,
      aroundShopDistance,
      aroundAirportName,
      aroundTrainName,
      aroundMetroName,
      aroundBusName,
      aroundShopName,
      checkInFrom,
      checkInTo,
      checkOutFrom,
      checkOutTo,
      useableArea,
      totalArea,
      timeVisitIn,
      timeVisitOut,
      dateVisitIn,
      dateVisitOut,
      overview,
      buyOrRent,
      nbRooms,
      nbBathrooms,
      nbGarage,
      price;
  bool? offerOrNot,
      caract,
      arround,
      checkprix,
      bacony,
      terace,
      toKnow,
      jardin,
      facilities,
      wifi,
      airCond,
      elevator,
      kitchenFacil,
      parking,
      tv;

  List<dynamic>? images;
  Annonce({
    this.id,
    this.ville,
    this.cite,
    this.categorie,
    this.title,
    this.aroundCityDistance,
    this.aroundAirportDistance,
    this.aroundTrainDistance,
    this.aroundMetroDistance,
    this.aroundBusDistance,
    this.aroundShopDistance,
    this.aroundAirportName,
    this.aroundTrainName,
    this.aroundMetroName,
    this.aroundBusName,
    this.aroundShopName,
    this.checkInFrom,
    this.checkInTo,
    this.checkOutFrom,
    this.checkOutTo,
    this.useableArea,
    this.totalArea,
    this.timeVisitIn,
    this.timeVisitOut,
    this.dateVisitIn,
    this.dateVisitOut,
    this.overview,
    this.buyOrRent,
    this.offerOrNot,
    this.bacony,
    this.terace,
    this.jardin,
    this.wifi,
    this.airCond,
    this.elevator,
    this.kitchenFacil,
    this.parking,
    this.tv,
    this.nbRooms,
    this.nbBathrooms,
    this.nbGarage,
    this.images,
    this.toKnow,
    this.facilities,
    this.checkprix,
    this.arround,
    this.caract,
    this.price,
  });

  Map<String, dynamic> toJson() {
    return {
      "id": id,
      "title": title,
      "ville": ville,
      "cite": cite,
      "categorie": categorie,
      "buyOrRent": buyOrRent,
      "Checkprix": checkprix,
      "around": arround,
      "useableArea": useableArea,
      "totalArea": totalArea,
      "nbRooms": nbRooms,
      "nbBathrooms": nbBathrooms,
      "nbGarage": nbGarage,
      "bacony": bacony,
      "terace": terace,
      "jardin": jardin,
      "aroundAirportDistance": aroundAirportDistance,
      "aroundCityDistance": aroundCityDistance,
      "aroundTrainDistance": aroundTrainDistance,
      "aroundMetroDistance": aroundMetroDistance,
      "aroundBusDistance": aroundBusDistance,
      "aroundShopDistance": aroundShopDistance,
      "aroundAirportName": aroundAirportName,
      "aroundTrainName": aroundTrainName,
      "aroundMetroName": aroundMetroName,
      "aroundBusName": aroundBusName,
      "aroundShopName": aroundShopName,
      "wifi": wifi,
      "tv": tv,
      "parking": parking,
      "checkInFrom": checkInFrom,
      "checkInTo": checkInTo,
      "checkOutFrom": checkOutFrom,
      "checkOutTo": checkOutTo,
      "timeVisitIn": timeVisitIn,
      "timeVisitOut": timeVisitOut,
      "dateVisitIn": dateVisitIn,
      "dateVisitOut": dateVisitOut,
      "toKnow": toKnow,
      "facilities": facilities,
      "overview": overview,
      "caract": caract,
      "price": price,
      "offerOrNot": offerOrNot,
    };
  }

  factory Annonce.fromSnapshot(
      DocumentSnapshot<Map<String, dynamic>> document, List<dynamic>? images) {
    final data = document.data()!;
    return Annonce(
      id: data["id"],
      title: data["title"],
      ville: data["ville"],
      cite: data["cite"],
      categorie: data["categorie"],
      buyOrRent: data["buyOrRent"],
      useableArea: data["useableArea"],
      totalArea: data["totalArea"],
      nbRooms: data["nbRooms"],
      nbBathrooms: data["nbBathrooms"],
      nbGarage: data["nbGarage"],
      bacony: data["bacony"],
      terace: data["terace"],
      aroundAirportDistance: data["aroundAirportDistance"],
      aroundCityDistance: data["aroundCityDistance"],
      aroundTrainDistance: data["aroundTrainDistance"],
      aroundMetroDistance: data["aroundMetroDistance"],
      aroundBusDistance: data["aroundBusDistance"],
      aroundShopDistance: data["aroundShopDistance"],
      aroundAirportName: data["aroundAirportName"],
      aroundTrainName: data["aroundTrainName"],
      aroundMetroName: data["aroundMetroName"],
      aroundBusName: data["aroundBusName"],
      aroundShopName: data["aroundShopName"],
      wifi: data["wifi"],
      tv: data["tv"],
      parking: data["parking"],
      checkInFrom: data["checkInFrom"],
      checkInTo: data["checkInTo"],
      checkOutFrom: data["checkOutFrom"],
      checkOutTo: data["checkOutTo"],
      timeVisitIn: data["timeVisitIn"],
      timeVisitOut: data["timeVisitOut"],
      dateVisitIn: data["dateVisitIn"],
      dateVisitOut: data["dateVisitOut"],
      toKnow: data["toKnow"],
      facilities: data["facilities"],
      images: images,
      overview: data["overview"],
      checkprix: data["checkprix"],
      arround: data["arround"],
      caract: data["caract"],
      jardin: data["jardin"],
      price: data["price"],
      offerOrNot: data["offerOrNot"],
    );
  }
}

List Annonces = [
  Annonce(
    title: "Large 1-room apartment with a beautiful terrace",
    ville: "Tunis",
    cite: "Bardo",
    categorie: "Appartement",
    buyOrRent: "Vente",
    useableArea: "340m²",
    totalArea: "500m²",
    nbRooms: "4",
    nbBathrooms: "2",
    nbGarage: "2",
    bacony: true,
    terace: false,
    aroundAirportDistance: "2.5km",
    aroundCityDistance: "700m",
    aroundTrainDistance: "1km",
    aroundMetroDistance: "340m",
    aroundBusDistance: "230m",
    aroundShopDistance: "130m",
    aroundAirportName: "Carthage",
    aroundTrainName: "Bercelone",
    aroundMetroName: "Beb Saadoun",
    aroundBusName: "Ibn khaldoun",
    aroundShopName: "Monoprix",
    wifi: true,
    tv: true,
    parking: true,
    checkInFrom: "15:00",
    checkInTo: "23:59",
    checkOutFrom: "07:00",
    checkOutTo: "10:00",
    timeVisitIn: "08:00",
    timeVisitOut: "18:00",
    dateVisitIn: "Monday",
    dateVisitOut: "Saturday",
    toKnow: true,
    facilities: true,
    images: [
      "assets/images/house1.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
    overview:
        "The Vibrant Mercado de La Boqueria Public Market is 10 minutes away by car, while Barcelona Pavilion is just close to the apartment. Unique Cozy Scenic Penthouse is within 550 feet of CaixaForum Barcelona Art Gallery and Barcelona-El Prat airport is 17 minutes’ drive away. Jaipur Palace Indian Restaurant pampers guests with Indian dishes and lies quite a walk from this property. Unique Cozy Scenic Penthouse apartment is not far from The Magic Fountain. The apartment is located within 1.9 miles of Passeig de Gràcia train station.",
  ),
  Annonce(
    title: "Large 2-room apartment with a beautiful terrace",
    ville: "Tunis",
    cite: "Bardo",
    categorie: "Appartement",
    buyOrRent: "Vente",
    useableArea: "340m²",
    totalArea: "500m²",
    nbRooms: "4",
    nbBathrooms: "2",
    nbGarage: "2",
    bacony: true,
    terace: false,
    aroundAirportDistance: "2.5km",
    aroundCityDistance: "700m",
    aroundTrainDistance: "1km",
    aroundMetroDistance: "340m",
    aroundBusDistance: "230m",
    aroundShopDistance: "130m",
    aroundAirportName: "Carthage",
    aroundTrainName: "Bercelone",
    aroundMetroName: "Beb Saadoun",
    aroundBusName: "Ibn khaldoun",
    aroundShopName: "Monoprix",
    wifi: true,
    tv: true,
    parking: true,
    checkInFrom: "15:00",
    checkInTo: "23:59",
    checkOutFrom: "07:00",
    checkOutTo: "10:00",
    timeVisitIn: "08:00",
    timeVisitOut: "18:00",
    dateVisitIn: "Monday",
    dateVisitOut: "Saturday",
    toKnow: true,
    facilities: true,
    images: [
      "assets/images/house1.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
    overview:
        "The Vibrant Mercado de La Boqueria Public Market is 10 minutes away by car, while Barcelona Pavilion is just close to the apartment. Unique Cozy Scenic Penthouse is within 550 feet of CaixaForum Barcelona Art Gallery and Barcelona-El Prat airport is 17 minutes’ drive away. Jaipur Palace Indian Restaurant pampers guests with Indian dishes and lies quite a walk from this property. Unique Cozy Scenic Penthouse apartment is not far from The Magic Fountain. The apartment is located within 1.9 miles of Passeig de Gràcia train station.",
  ),
  Annonce(
    title: "Large 3-room apartment with a beautiful terrace",
    ville: "Tunis",
    cite: "Bardo",
    categorie: "Appartement",
    buyOrRent: "Vente",
    useableArea: "340m²",
    totalArea: "500m²",
    nbRooms: "4",
    nbBathrooms: "2",
    nbGarage: "2",
    bacony: true,
    terace: false,
    aroundAirportDistance: "2.5km",
    aroundCityDistance: "700m",
    aroundTrainDistance: "1km",
    aroundMetroDistance: "340m",
    aroundBusDistance: "230m",
    aroundShopDistance: "130m",
    aroundAirportName: "Carthage",
    aroundTrainName: "Bercelone",
    aroundMetroName: "Beb Saadoun",
    aroundBusName: "Ibn khaldoun",
    aroundShopName: "Monoprix",
    wifi: true,
    tv: true,
    parking: true,
    checkInFrom: "15:00",
    checkInTo: "23:59",
    checkOutFrom: "07:00",
    checkOutTo: "10:00",
    timeVisitIn: "08:00",
    timeVisitOut: "18:00",
    dateVisitIn: "Monday",
    dateVisitOut: "Saturday",
    toKnow: true,
    facilities: true,
    images: [
      "assets/images/house1.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
    overview:
        "The Vibrant Mercado de La Boqueria Public Market is 10 minutes away by car, while Barcelona Pavilion is just close to the apartment. Unique Cozy Scenic Penthouse is within 550 feet of CaixaForum Barcelona Art Gallery and Barcelona-El Prat airport is 17 minutes’ drive away. Jaipur Palace Indian Restaurant pampers guests with Indian dishes and lies quite a walk from this property. Unique Cozy Scenic Penthouse apartment is not far from The Magic Fountain. The apartment is located within 1.9 miles of Passeig de Gràcia train station.",
  ),
  Annonce(
    title: "Large 4-room apartment with a beautiful terrace",
    ville: "Tunis",
    cite: "Bardo",
    categorie: "Appartement",
    buyOrRent: "Vente",
    useableArea: "340m²",
    totalArea: "500m²",
    nbRooms: "4",
    nbBathrooms: "2",
    nbGarage: "2",
    bacony: true,
    terace: false,
    aroundAirportDistance: "2.5km",
    aroundCityDistance: "700m",
    aroundTrainDistance: "1km",
    aroundMetroDistance: "340m",
    aroundBusDistance: "230m",
    aroundShopDistance: "130m",
    aroundAirportName: "Carthage",
    aroundTrainName: "Bercelone",
    aroundMetroName: "Beb Saadoun",
    aroundBusName: "Ibn khaldoun",
    aroundShopName: "Monoprix",
    wifi: true,
    tv: true,
    parking: true,
    checkInFrom: "15:00",
    checkInTo: "23:59",
    checkOutFrom: "07:00",
    checkOutTo: "10:00",
    timeVisitIn: "08:00",
    timeVisitOut: "18:00",
    dateVisitIn: "Monday",
    dateVisitOut: "Saturday",
    toKnow: true,
    facilities: true,
    images: [
      "assets/images/house1.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
    overview:
        "The Vibrant Mercado de La Boqueria Public Market is 10 minutes away by car, while Barcelona Pavilion is just close to the apartment. Unique Cozy Scenic Penthouse is within 550 feet of CaixaForum Barcelona Art Gallery and Barcelona-El Prat airport is 17 minutes’ drive away. Jaipur Palace Indian Restaurant pampers guests with Indian dishes and lies quite a walk from this property. Unique Cozy Scenic Penthouse apartment is not far from The Magic Fountain. The apartment is located within 1.9 miles of Passeig de Gràcia train station.",
  ),
  Annonce(
    title: "Large 5-room apartment with a beautiful terrace",
    ville: "Tunis",
    cite: "Bardo",
    categorie: "Appartement",
    buyOrRent: "Vente",
    useableArea: "340m²",
    totalArea: "500m²",
    nbRooms: "4",
    nbBathrooms: "2",
    nbGarage: "2",
    bacony: true,
    terace: false,
    aroundAirportDistance: "2.5km",
    aroundCityDistance: "700m",
    aroundTrainDistance: "1km",
    aroundMetroDistance: "340m",
    aroundBusDistance: "230m",
    aroundShopDistance: "130m",
    aroundAirportName: "Carthage",
    aroundTrainName: "Bercelone",
    aroundMetroName: "Beb Saadoun",
    aroundBusName: "Ibn khaldoun",
    aroundShopName: "Monoprix",
    wifi: true,
    tv: true,
    parking: true,
    checkInFrom: "15:00",
    checkInTo: "23:59",
    checkOutFrom: "07:00",
    checkOutTo: "10:00",
    timeVisitIn: "08:00",
    timeVisitOut: "18:00",
    dateVisitIn: "Monday",
    dateVisitOut: "Saturday",
    toKnow: true,
    facilities: true,
    images: [
      "assets/images/house1.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
    overview:
        "The Vibrant Mercado de La Boqueria Public Market is 10 minutes away by car, while Barcelona Pavilion is just close to the apartment. Unique Cozy Scenic Penthouse is within 550 feet of CaixaForum Barcelona Art Gallery and Barcelona-El Prat airport is 17 minutes’ drive away. Jaipur Palace Indian Restaurant pampers guests with Indian dishes and lies quite a walk from this property. Unique Cozy Scenic Penthouse apartment is not far from The Magic Fountain. The apartment is located within 1.9 miles of Passeig de Gràcia train station.",
  ),
  Annonce(
    title: "Large 6-room apartment with a beautiful terrace",
    ville: "Tunis",
    cite: "Bardo",
    categorie: "Appartement",
    buyOrRent: "Vente",
    useableArea: "340m²",
    totalArea: "500m²",
    nbRooms: "4",
    nbBathrooms: "2",
    nbGarage: "2",
    bacony: true,
    terace: false,
    aroundAirportDistance: "2.5km",
    aroundCityDistance: "700m",
    aroundTrainDistance: "1km",
    aroundMetroDistance: "340m",
    aroundBusDistance: "230m",
    aroundShopDistance: "130m",
    aroundAirportName: "Carthage",
    aroundTrainName: "Bercelone",
    aroundMetroName: "Beb Saadoun",
    aroundBusName: "Ibn khaldoun",
    aroundShopName: "Monoprix",
    wifi: true,
    tv: true,
    parking: true,
    checkInFrom: "15:00",
    checkInTo: "23:59",
    checkOutFrom: "07:00",
    checkOutTo: "10:00",
    timeVisitIn: "08:00",
    timeVisitOut: "18:00",
    dateVisitIn: "Monday",
    dateVisitOut: "Saturday",
    toKnow: true,
    facilities: true,
    images: [
      "assets/images/house1.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
    overview:
        "The Vibrant Mercado de La Boqueria Public Market is 10 minutes away by car, while Barcelona Pavilion is just close to the apartment. Unique Cozy Scenic Penthouse is within 550 feet of CaixaForum Barcelona Art Gallery and Barcelona-El Prat airport is 17 minutes’ drive away. Jaipur Palace Indian Restaurant pampers guests with Indian dishes and lies quite a walk from this property. Unique Cozy Scenic Penthouse apartment is not far from The Magic Fountain. The apartment is located within 1.9 miles of Passeig de Gràcia train station.",
  ),
  Annonce(
    title: "Large 7-room apartment with a beautiful terrace",
    ville: "Tunis",
    cite: "Menzah",
    categorie: "Terrain",
    buyOrRent: "Location",
    useableArea: "500m²",
    totalArea: "500m²",
    nbRooms: "0",
    nbBathrooms: "0",
    nbGarage: "0",
    bacony: false,
    terace: false,
    aroundAirportDistance: "2.5km",
    aroundCityDistance: "700m",
    aroundTrainDistance: "",
    aroundMetroDistance: "",
    aroundBusDistance: "",
    aroundShopDistance: "",
    aroundAirportName: "Carthage",
    aroundTrainName: "",
    aroundMetroName: "",
    aroundBusName: "",
    aroundShopName: "",
    wifi: true,
    tv: true,
    parking: true,
    checkInFrom: "",
    checkInTo: "",
    checkOutFrom: "",
    checkOutTo: "",
    timeVisitIn: "08:00",
    timeVisitOut: "18:00",
    dateVisitIn: "Monday",
    dateVisitOut: "Saturday",
    toKnow: false,
    facilities: false,
    images: [
      "assets/images/house1.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
    overview:
        "The Vibrant Mercado de La Boqueria Public Market is 10 minutes away by car, while Barcelona Pavilion is just close to the apartment. Unique Cozy Scenic Penthouse is within 550 feet of CaixaForum Barcelona Art Gallery and Barcelona-El Prat airport is 17 minutes’ drive away. Jaipur Palace Indian Restaurant pampers guests with Indian dishes and lies quite a walk from this property. Unique Cozy Scenic Penthouse apartment is not far from The Magic Fountain. The apartment is located within 1.9 miles of Passeig de Gràcia train station.",
  ),
];
