// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq4Ri9FlVMBJAPCFE2q0hQsmta23AZbZg',
    appId: '1:18378059737:web:39c6937e73cbec305d33c8',
    messagingSenderId: '18378059737',
    projectId: 'immobarcide-f0e0e',
    authDomain: 'immobarcide-f0e0e.firebaseapp.com',
    storageBucket: 'immobarcide-f0e0e.appspot.com',
    measurementId: 'G-EP7M4W8ZNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxJH1pjZ61veblAx_QPxEkAT8vESmYk1Q',
    appId: '1:18378059737:android:d66d73dc18cfafa65d33c8',
    messagingSenderId: '18378059737',
    projectId: 'immobarcide-f0e0e',
    storageBucket: 'immobarcide-f0e0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiwZXboucvJvkXwDRoxRv27K8TKThjWMA',
    appId: '1:18378059737:ios:08701ed150488c825d33c8',
    messagingSenderId: '18378059737',
    projectId: 'immobarcide-f0e0e',
    storageBucket: 'immobarcide-f0e0e.appspot.com',
    iosClientId: '18378059737-3imjnh9gpn4fl4gplk6134opnq5jo43s.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminimmobarcide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiwZXboucvJvkXwDRoxRv27K8TKThjWMA',
    appId: '1:18378059737:ios:4e8c94cff85d6a445d33c8',
    messagingSenderId: '18378059737',
    projectId: 'immobarcide-f0e0e',
    storageBucket: 'immobarcide-f0e0e.appspot.com',
    iosClientId: '18378059737-gs4tgkj9bbgviuv0t5cbcik3hf9e4i69.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminimmobarcide.RunnerTests',
  );
}
