class Offer {
  final String? image,
      title,
      price,
      city,
      properityType,
      size,
      street,
      garage,
      type,
      rooms,
      usableArea,
      totalArea,
      numOfBathrooms,
      Tdescription,
      Tcharacteristics,
      Tsolution,
      Texecution,
      Tlocation,
      Tfedors;
  bool? insoluted, balcony, terrace;
  final listImage;

  Offer(
      {this.image,
      this.listImage,
      this.title,
      this.price,
      this.city,
      this.properityType,
      this.size,
      this.street,
      this.garage,
      this.type,
      this.rooms,
      this.usableArea,
      this.totalArea,
      this.numOfBathrooms,
      this.Tdescription,
      this.Tcharacteristics,
      this.Tsolution,
      this.Texecution,
      this.Tlocation,
      this.Tfedors});
}

List Offers = [
  Offer(
    image: "assets/images/house1.png",
    title: "Large 4-room apartment with a beautiful terrace",
    price: "320 000",
    city: "Barcelona IX. ",
    listImage: [
      "assets/images/house1.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
  ),
  Offer(
    image: "assets/images/house2.png",
    title: "5i large design apartment with terrace",
    price: "280 000",
    city: "Madrid VI. ",
    listImage: [
      "assets/images/house2.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
  ),
  Offer(
    image: "assets/images/house2.png",
    title: "3-room apartment with a beautiful terrace",
    price: "350 000",
    city: "Madrid II. ",
    listImage: [
      "assets/images/house2.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
  ),
  Offer(
    image: "assets/images/house4.png",
    title: "Magnificent duplex in a private villa",
    price: "280 000",
    city: "Barcelona IV. ",
    listImage: [
      "assets/images/house4.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
  ),
  Offer(
    image: "assets/images/house1.png",
    title: "Large 4-room apartment with a beautiful terrace",
    price: "320 000",
    city: "Barcelona IX. ",
    listImage: [
      "assets/images/house1.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
  ),
  Offer(
    image: "assets/images/house2.png",
    title: "5i large design apartment with terrace",
    price: "280 000",
    city: "Madrid VI. ",
    listImage: [
      "assets/images/house2.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
  ),
  Offer(
    image: "assets/images/house1.png",
    title: "Large 4-room apartment with a beautiful terrace",
    price: "320 000",
    city: "Barcelona IX. ",
    listImage: [
      "assets/images/house1.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
  ),
  Offer(
    image: "assets/images/house2.png",
    title: "5i large design apartment with terrace",
    price: "280 000",
    city: "Madrid VI. ",
    listImage: [
      "assets/images/house2.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
  ),
  Offer(
    image: "assets/images/house2.png",
    title: "3-room apartment with a beautiful terrace",
    price: "350 000",
    city: "Madrid II. ",
    listImage: [
      "assets/images/house2.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
  ),
  Offer(
    image: "assets/images/house4.png",
    title: "Magnificent duplex in a private villa",
    price: "280 000",
    city: "Barcelona IV. ",
    listImage: [
      "assets/images/house4.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
  ),
  Offer(
    image: "assets/images/house1.png",
    title: "Large 4-room apartment with a beautiful terrace",
    price: "320 000",
    city: "Barcelona IX. ",
    listImage: [
      "assets/images/house1.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
  ),
  Offer(
    image: "assets/images/house2.png",
    title: "5i large design apartment with terrace",
    price: "280 000",
    city: "Madrid VI. ",
    listImage: [
      "assets/images/house2.png",
      "assets/images/ad_image/adImage1.jpg",
      "assets/images/ad_image/adImage2.jpg",
      "assets/images/ad_image/adImage3.jpg",
      "assets/images/ad_image/adImage4.jpg",
    ],
  ),
];
